#!/bin/sh
#
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
#
# foxreview_uninit
# 
# Copyright  (C) 2009~2010 Foxreview <foxreview@googlecode.com> All Rights Reserved.
#
#
# This script is free software; you can redistribute it and/or
# modify it under the terms of the GNU Library General Public
# License as published by the Free Software Foundation; either
# version 2 of the License, or (at your option) any later version.
#
# This script is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Library General Public License for more details.
#
# You should have received a copy of the GNU Library General Public
# License along with this library; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place - Suite 330,
# Boston, MA 02111-1307, USA, or look at the website 
# http://www.gnu.org/copyleft/gpl.html


########################################################################
##  foxreview version info                                            ##
########################################################################
FOXREVIEW_VERSION_NUMBER='0.1'

########################################################################
## setting path for  installing foxreview config                      ##
########################################################################
function uninstall()
{
    CONFIG_DIR=
    WORK_DIR=
    local DEFAULT_DIR=~/.foxreview
    local DEFAULT_CONFIG=~/.foxreview/CONFIG
    local ANSWER
    
    #get config and work path 
    if [ -f $DEFAULT_CONFIG ];then
        CONFIG_DIR=$(sed -n "1 p" $DEFAULT_CONFIG | awk -F= '{print $2}' )
        WORK_DIR=$(sed -n "2 p" $DEFAULT_CONFIG | awk -F= '{print $2}' )
    else
        echo "foxreview $FOXREVIEW_VERSION_NUMBER"
        echo " "
        echo "You had not initialized your foxreview $FOXREVIEW_VERSION_NUMBER config. "
        exit
    fi
 
    #notice information
    echo "Do you want to uninstall foxreview $FOXREVIEW_VERSION_NUMBER ? (yes [y] or no [n])"
    
    read ANSWER
        
    #according to ANSWER 
    if [ "$ANSWER" = "yes" ] || [ "$ANSWER" = "y" ];then
        #remove directory
        #rm -rf $CONFIG_DIR
        #rm -rf $WORK_DIR
        rm -rf $DEFAULT_DIR
       
        #check rm result
        if [ "$?" = 0 ];then
            echo "   "
            echo "Uninitialize foxreview $FOXREVIEW_VERSION_NUMBER success !"
        else
            echo "Uninitialize foxreview $FOXREVIEW_VERSION_NUMBER fail !"
        fi
    elif [ "$ANSWER" = "no" ] || [ "$ANSWER" = "n" ] ; then
        echo "    "
        echo "Bye "
        exit
    else
        echo "please re-run foxreview_uninit and input yes or no !" 
    fi
}



########################################################################
## foxreview_uninit main process                                      ##
########################################################################
case "$#" in
    0) uninstall 
       ;;
    *) printf "foxreview $foxreview_VERSION_NUMBER \n"
       printf "Usage: foxreview_uninit  \n"
       echo   "Uninitialize foxreview running environment "
       echo "                              "
       echo "Report bugs to the author <foxreview@googlecode.com>"
       ;;
esac

